name:         uniform-algebras
version:      0.0.10.0
license:      GPL
maintainer:   Andrew U. Frank <frank@geoinfo.tuwien.ac.at>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     Algebra
synopsis:     simplistic algebras, eg. zero
description: |
    simple algebras without much mathematical underpinning
      - zero with test isZero, notZero (not a semigroupoid)
          exports also Maybe and Either
      - pointless operations, e.g. tuples up to 4 or 5
      - ListForms (a monoid)

# Please see the README on GitHub at <https://github.com/andrewufrank/uniform-algebras/readme>

# verbatim:
#   cabal-version: 3.0

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: 
    - .

# this is only a library, no directly executable

# there are no tests used so far:
# tests:
#   algebra-test:
#     main:                Testing.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - HTF
#     - uniform-algebras
#     - uniform-error
